### ISSUE TITLE
state of the book and code review

### ISSUE THREAD

**Issue by andreacortis** [RobertRosenbaum/ModelingNeuralCircuits#1]
Hello Robert,

I am reading the pdf version of your book, and I am finding it really interesting.
If you can say that, I wanted to know what the status of the book and code review is.

While I am trying to follow on the jupyter notebooks, it appears that there are several inconsistencies (and I just run the `LeakyIntegrator`)

For instance, I believe that the code for the voltage `V` in eq (1.4) and corresponding to the plots in Figure 1.2 should be

```
V = EL+np.convolve(Ix,k,mode='same')*dt # errata
V = (V0 - EL)*np.exp(-time/taum) + np.convolve(Ix,k,mode='same')*dt + EL # corrige
```

Also the plots axis seem to be messed up, and I had to spend some time reworking them.

As an observation, while technically correct because of the rescaling, it is very confusing to see `current` measure in `volts`.

Hopefully, the book's printed version will see these issues (and probably others in the rest of the notebooks) resolved.

Wish you success!

Andrea

**Comment by RobertRosenbaum** [comment]
Thanks for the comments. I just finished teaching a course using this book and code. I made several corrections to the code and book along the way, including the error you pointed out in LeakyIntegrator.ipynb

I'm not sure what you mean about the axis, but please clarify if you want.

That's a good point about measuring current in volts. Maybe it would be better not to label the units on axes with currents ( ie, not write "(mV)" on those axes). Unfortunately, the final draft of the book has already been submitted to the publishers, so I can't change that now, but I made a note and will consider the change if/when there is a 2nd edition. 

The book will be published by MIT Press sometime in 2024, but I don't know the date yet.
